%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/brycelittle/Dropbox/research/macrofinance/dynhoe/data/Y1_out_qtr.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/07/05 12:38:49

%% Import the data
% [~, ~, raw] = xlsread('/Users/brycelittle/Dropbox/research/macrofinance/dynhoe/data/Y1_out_qtr.xlsx','Sheet1');
[~, ~, raw] = xlsread('C:/Users/bryce/Dropbox/Research/macrofinance/dynhoe/data/Y1_out_qtr.xlsx','Sheet1');
raw = raw(2:end,:);

%% Create output variable
Y1 = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;