%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/brycelittle/Dropbox/research/macrofinance/dynhoe/data/Y2_out_qtr.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/07/05 12:40:38

%% Import the data
% [~, ~, raw] = xlsread('/Users/brycelittle/Dropbox/research/macrofinance/dynhoe/data/Y2_out_qtr.xlsx','Sheet1');
[~, ~, raw] = xlsread('C:/Users/bryce/Dropbox/Research/macrofinance/dynhoe/data/Y2_out_qtr.xlsx','Sheet1');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
Y2 = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw R;